apiVersion: 1

contactPoints:
  - orgId: 1
    name: ntfy-security
    receivers:
      - uid: ntfy-security
        type: webhook
        settings:
          url: http://ntfy:80/homelab-vulns
          httpMethod: POST
          authorization_scheme: none
          httpHeaders:
            - name: Title
              value: "üõ°Ô∏è Trivy Security Alert"
            - name: Priority
              value: "4"
            - name: Tags
              value: "security,trivy,warning"
        disableResolveMessage: false
