authHTTPAddress: null
authHTTPExclude:
- action: api
- action: metrics
- action: pprof
authInternalUsers:
- ips:
  - 127.0.0.1
  permissions:
  - action: read
  - action: publish
- permissions:
  - action: read
authJWTClaimKey: mediamtx_permissions
authJWTJWKS: null
authMethod: internal
encryption: 'no'
hls: true
hlsAddress: :8888
hlsAllowOrigin: '*'
hlsAlwaysRemux: false
hlsDirectory: ''
hlsEncryption: false
hlsMuxerCloseAfter: 60s
hlsPartDuration: 200ms
hlsSegmentCount: 7
hlsSegmentDuration: 1s
hlsSegmentMaxSize: 50M
hlsServerCert: server.crt
hlsServerKey: server.key
hlsVariant: lowLatency
logDestinations:
- stdout
logFile: mediamtx.log
logLevel: info
metrics: false
metricsAddress: :9998
metricsAllowOrigin: '*'
metricsEncryption: false
metricsServerCert: server.crt
metricsServerKey: server.key
multicastIPRange: 224.1.0.0/16
multicastRTCPPort: 8003
multicastRTPPort: 8002
pathDefaults:
  fallback: null
  maxReaders: 0
  overridePublisher: true
  record: false
  recordDeleteAfter: 0s
  recordFormat: fmp4
  recordPartDuration: 1s
  recordPath: /record/%path/%Y-%m-%d_%H-%M-%S
  recordSegmentDuration: 60s
  rpiCameraAWB: auto
  rpiCameraAWBGains:
  - 0
  - 0
  rpiCameraAfMode: continuous
  rpiCameraAfRange: normal
  rpiCameraAfSpeed: normal
  rpiCameraAfWindow: null
  rpiCameraBitrate: 1000000
  rpiCameraBrightness: 0
  rpiCameraCamID: 0
  rpiCameraCodec: auto
  rpiCameraContrast: 1
  rpiCameraDenoise: 'off'
  rpiCameraEV: 0
  rpiCameraExposure: normal
  rpiCameraFPS: 30
  rpiCameraFlickerPeriod: 0
  rpiCameraGain: 0
  rpiCameraHDR: false
  rpiCameraHFlip: false
  rpiCameraHeight: 1080
  rpiCameraIDRPeriod: 60
  rpiCameraLensPosition: 0.0
  rpiCameraLevel: '4.1'
  rpiCameraMetering: centre
  rpiCameraMode: null
  rpiCameraProfile: main
  rpiCameraROI: null
  rpiCameraSaturation: 1
  rpiCameraSharpness: 1
  rpiCameraShutter: 0
  rpiCameraTextOverlay: '%Y-%m-%d %H:%M:%S - MediaMTX'
  rpiCameraTextOverlayEnable: false
  rpiCameraTuningFile: null
  rpiCameraVFlip: false
  rpiCameraWidth: 1920
  rtspAnyPort: false
  rtspRangeStart: null
  rtspRangeType: null
  rtspTransport: automatic
  runOnDemand: null
  runOnDemandCloseAfter: 60s
  runOnDemandRestart: false
  runOnDemandStartTimeout: 30s
  runOnInit: null
  runOnInitRestart: false
  runOnNotReady: bash -c 'echo $MTX_PATH,NotReady! > /tmp/mtx_event;'
  runOnRead: bash -c 'echo $MTX_PATH,Read! > /tmp/mtx_event;'
  runOnReadRestart: false
  runOnReady: bash -c 'echo $MTX_PATH,Ready! > /tmp/mtx_event;'
  runOnReadyRestart: false
  runOnRecordSegmentComplete: null
  runOnRecordSegmentCreate: null
  runOnUnDemand: null
  runOnUnread: bash -c 'echo $MTX_PATH,Unread! > /tmp/mtx_event;'
  source: publisher
  sourceFingerprint: null
  sourceOnDemand: false
  sourceOnDemandCloseAfter: 10s
  sourceOnDemandStartTimeout: 10s
  sourceRedirect: null
  srtPublishPassphrase: null
  srtReadPassphrase: null
paths:
  baby-room:
    runOnDemand: bash -c 'echo $MTX_PATH,start! > /tmp/mtx_event'
    runOnUnDemand: bash -c 'echo $MTX_PATH,stop! > /tmp/mtx_event'
  front-door-cam:
    runOnDemand: bash -c 'echo $MTX_PATH,start! > /tmp/mtx_event'
    runOnUnDemand: bash -c 'echo $MTX_PATH,stop! > /tmp/mtx_event'
  living-room-cam:
    runOnDemand: bash -c 'echo $MTX_PATH,start! > /tmp/mtx_event'
    runOnUnDemand: bash -c 'echo $MTX_PATH,stop! > /tmp/mtx_event'
  patio-cam:
    runOnDemand: bash -c 'echo $MTX_PATH,start! > /tmp/mtx_event'
    runOnUnDemand: bash -c 'echo $MTX_PATH,stop! > /tmp/mtx_event'
playback: false
playbackAddress: :9996
playbackAllowOrigin: '*'
playbackEncryption: false
playbackServerCert: server.crt
playbackServerKey: server.key
pprof: false
pprofAddress: :9999
pprofAllowOrigin: '*'
pprofEncryption: false
pprofServerCert: server.crt
pprofServerKey: server.key
protocols:
- udp
- multicast
- tcp
readTimeout: 10s
rtcpAddress: :8001
rtmp: true
rtmpAddress: :1935
rtmpEncryption: 'no'
rtmpServerCert: server.crt
rtmpServerKey: server.key
rtmpsAddress: :1936
rtpAddress: :8000
rtsp: true
rtspAddress: :8554
rtspAuthMethods:
- basic
rtspsAddress: :8322
runOnConnect: null
runOnConnectRestart: false
runOnDisconnect: null
serverCert: server.crt
serverKey: server.key
srt: true
srtAddress: :8890
udpMaxPayloadSize: 1472
webrtc: true
webrtcAdditionalHosts:
- 192.168.1.11
webrtcAddress: :8889
webrtcAllowOrigin: '*'
webrtcEncryption: false
webrtcHandshakeTimeout: 10s
webrtcICEServers2: []
webrtcIPsFromInterfaces: true
webrtcIPsFromInterfacesList: []
webrtcLocalTCPAddress: ''
webrtcLocalUDPAddress: :8189
webrtcServerCert: server.crt
webrtcServerKey: server.key
webrtcTrackGatherTimeout: 2s
writeQueueSize: 512
writeTimeout: 10s
