services:
  immich-server:
    healthcheck:
      test: ["CMD-SHELL", "(curl -fsS http://127.0.0.1:2283/api/server/ping >/dev/null 2>&1) || (wget -qO- http://127.0.0.1:2283/api/server/ping >/dev/null)"]
      interval: 10s
      timeout: 5s
      retries: 10
