services:
  immich-redis:
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -u 'redis://default:${REDIS_PASSWORD}@127.0.0.1:6379' ping | grep -q PONG"]
      interval: 10s
      timeout: 5s
      retries: 5
