global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "container_memory_alerts.yml"
  - "tracker-enrollment-alerts.yml"

scrape_configs:
  - job_name: 'blackbox-http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://192.168.1.11:3030 # grafana
          - http://192.168.1.11:9090 # prometheus
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
  - job_name: process-exporter
    static_configs:
      - targets:
          - 192.168.1.11:9256
  - job_name: intel-gpu
    static_configs:
      - targets:
          - 192.168.1.11:8082
  - job_name: tempo
    static_configs:
      - targets: ['tempo:3200']
  - job_name: falcosidekick
    static_configs:
      - targets: ['falcosidekick:2801']
  - job_name: pushgateway
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']
  - job_name: 'pve'
    metrics_path: /pve
    params:
      target: ['192.168.1.10']
    static_configs:
      - targets: ['pve-exporter:9221']
